Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/var/pyenv/versions/3.8.2/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
function solve!(ss, acc, β, nsweeps, ntherm, niters_meas, rng)
    for isweep in 1:nsweeps
        MC.update!(ss, β, niters_meas, rng)
        if isweep <= ntherm
            continue
        end
        Meas.add!(acc, "E", Float64(ss.energy))
        Meas.add!(acc, "E2", Float64(ss.energy)^2)
        MC.sanity_check(ss)
    end
end


nsweeps = 100
niters_meas = 10
ntherm = ceil(nsweeps/10)
β = 1.0

ss = MC.SpinState(s0)
acc = Meas.Accumulator()
solve!(ss, acc, β, nsweeps, ntherm, niters_meas, rng)

println(Meas.mean(acc, "E"))
println(Meas.mean(acc, "E2"))
------------------

MethodError: no method matching copyto!(::Float64, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{},typeof(+),Tuple{Float64,Float64}})
Closest candidates are:
  copyto!(!Matched::AbstractArray, ::Base.Broadcast.Broadcasted{var"#s828",Axes,F,Args} where Args<:Tuple where F where Axes where var"#s828"<:Base.Broadcast.AbstractArrayStyle{0}) at broadcast.jl:889
  copyto!(!Matched::AbstractArray, ::Base.Broadcast.Broadcasted) at broadcast.jl:886
  copyto!(!Matched::AbstractArray, ::Any) at abstractarray.jl:730

Stacktrace:
 [1] materialize! at ./broadcast.jl:848 [inlined]
 [2] materialize!(::Float64, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Nothing,typeof(+),Tuple{Float64,Float64}}) at ./broadcast.jl:845
 [3] add!(::Main.Meas.Accumulator, ::String, ::Float64) at ./In[6]:21
 [4] solve!(::Main.MC.SpinState, ::Main.Meas.Accumulator, ::Float64, ::Int64, ::Float64, ::Int64, ::MersenneTwister) at ./In[7]:7
 [5] top-level scope at In[7]:21
 [6] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
LoadError: MethodError: no method matching copyto!(::Float64, ::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0},Tuple{},typeof(+),Tuple{Float64,Float64}})
Closest candidates are:
  copyto!(!Matched::AbstractArray, ::Base.Broadcast.Broadcasted{var"#s828",Axes,F,Args} where Args<:Tuple where F where Axes where var"#s828"<:Base.Broadcast.AbstractArrayStyle{0}) at broadcast.jl:889
  copyto!(!Matched::AbstractArray, ::Base.Broadcast.Broadcasted) at broadcast.jl:886
  copyto!(!Matched::AbstractArray, ::Any) at abstractarray.jl:730

